export const glossary = [
  { term: "LangGraph", simple: "A flowchart-like tool for building AI systems that take several steps.", details: "It helps teams build stateful AI workflows and control different conversation paths.", benefits: "Useful for complex support automation and repeatable multi-step workflows.", drawbacks: "Needs technical setup and careful testing.", alternatives: "LangChain, Haystack, or a fixed workflow." },
  { term: "PTU", simple: "Reserved AI computing capacity, similar to booking dedicated lanes for your requests.", details: "Provisioned Throughput Units provide predictable model capacity instead of purely pay-as-you-go usage.", benefits: "Predictable performance for steady, high-volume workloads.", drawbacks: "Can cost more when the reserved capacity is underused.", alternatives: "Pay-per-token or pay-per-request pricing." },
  { term: "Caching", simple: "Saving an answer so the AI does not repeat the same work.", details: "Applications reuse previous model outputs or prompt prefixes to reduce repeated computation.", benefits: "Lower cost and faster responses.", drawbacks: "Saved answers may become stale or inappropriate for a new context.", alternatives: "Real-time processing or deterministic rules." },
  { term: "Vector Database", simple: "A smart filing cabinet that finds information with similar meaning.", details: "It stores numeric representations called embeddings and searches for semantic similarity.", benefits: "Powers semantic search, recommendations, and RAG.", drawbacks: "Adds infrastructure and requires good retrieval design.", alternatives: "Keyword search or a traditional database with filters." },
  { term: "RAG", simple: "Giving AI an open-book test using trusted information before it answers.", details: "Retrieval-Augmented Generation finds relevant source material and passes it to a model as context.", benefits: "More current, grounded answers without retraining a model.", drawbacks: "Bad source material or retrieval produces bad answers.", alternatives: "Fine-tuning, long-context prompts, or curated workflows." },
  { term: "Hallucination", simple: "When AI confidently says something that is not true.", details: "The model generates information unsupported by its input or reliable evidence.", benefits: "None; measuring it helps teams track reliability.", drawbacks: "It can mislead users and damage trust.", alternatives: "RAG, citations, constrained answers, and human review." },
  { term: "Tokens", simple: "Small pieces of text that an AI reads and writes.", details: "Models split text into tokens, which providers also use for limits and pricing.", benefits: "Makes usage measurable.", drawbacks: "Counts are unintuitive and differ by model and language.", alternatives: "Word, character, or request-based limits." },
  { term: "Fine-tuning", simple: "Extra training that makes an existing AI better at one specific job.", details: "A model is updated using curated examples for a narrower task or behavior.", benefits: "More consistent specialized outputs and shorter prompts.", drawbacks: "Needs quality data, evaluation, and ongoing maintenance.", alternatives: "Prompt engineering, RAG, or few-shot examples." },
  { term: "Embeddings", simple: "Turning meaning into numbers so AI can compare information.", details: "Embeddings are numeric vectors used to find related content.", benefits: "Useful for search, clustering, recommendations, and RAG.", drawbacks: "They require storage and do not explain similarity decisions.", alternatives: "Keyword search, metadata filters, or rules." },
  { term: "Context Window", simple: "How much information an AI can keep in mind at once.", details: "It is the maximum number of tokens a model can process in one request.", benefits: "Larger windows can handle longer documents and conversations.", drawbacks: "More context costs more and does not guarantee better attention.", alternatives: "Summarization, RAG, or conversation memory." },
  { term: "AI Agent", simple: "AI that can choose steps and use tools to reach a goal.", details: "An agent combines a model with instructions and tools for multi-step tasks.", benefits: "Can automate workflows involving several decisions.", drawbacks: "Harder to predict, test, and control than a simple chatbot.", alternatives: "Fixed workflows, rule engines, or standard chatbots." },
  { term: "Guardrails", simple: "Rules and checks that keep AI answers safe and useful.", details: "They validate inputs and outputs against safety, policy, quality, and business requirements.", benefits: "Improves safety, consistency, and compliance.", drawbacks: "Can block useful responses and needs continual tuning.", alternatives: "Human moderation, strict prompts, or limited access." },
];

export const models = [
  { name: "GPT-4", provider: "OpenAI", type: "text", pricing: "paid", priceDetails: "$0.03 per 1K input tokens and $0.06 per 1K output tokens", useCases: "customer support, content generation, coding, analysis", strengths: "Strong reasoning and instruction following", limitations: "Can be expensive at high volume and sometimes verbose" },
  { name: "Claude 3.5 Sonnet", provider: "Anthropic", type: "text", pricing: "paid", priceDetails: "$3 per million input tokens and $15 per million output tokens", useCases: "complex reasoning, analysis, writing, coding", strengths: "Strong analysis, safety, and clear writing", limitations: "Availability varies and its ecosystem is smaller" },
  { name: "Gemini Pro", provider: "Google", type: "multimodal", pricing: "freemium", priceDetails: "A limited free tier with paid higher usage", useCases: "text generation, image analysis, multimodal tasks", strengths: "Handles images and text and integrates with Google services", limitations: "Free usage is limited and output quality can vary" },
  { name: "Whisper", provider: "OpenAI", type: "voice", pricing: "free", priceDetails: "Open source and free to self-host", useCases: "speech-to-text, transcription, voice interfaces", strengths: "Accurate, multilingual transcription", limitations: "Requires technical setup and basic versions lack real-time streaming" },
];