// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/tools/explain-jargon.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z } from "npm:zod@^4.6.2";

// src/lib/mcp/knowledge.ts
var glossary = [
  { term: "LangGraph", simple: "A flowchart-like tool for building AI systems that take several steps.", details: "It helps teams build stateful AI workflows and control different conversation paths.", benefits: "Useful for complex support automation and repeatable multi-step workflows.", drawbacks: "Needs technical setup and careful testing.", alternatives: "LangChain, Haystack, or a fixed workflow." },
  { term: "PTU", simple: "Reserved AI computing capacity, similar to booking dedicated lanes for your requests.", details: "Provisioned Throughput Units provide predictable model capacity instead of purely pay-as-you-go usage.", benefits: "Predictable performance for steady, high-volume workloads.", drawbacks: "Can cost more when the reserved capacity is underused.", alternatives: "Pay-per-token or pay-per-request pricing." },
  { term: "Caching", simple: "Saving an answer so the AI does not repeat the same work.", details: "Applications reuse previous model outputs or prompt prefixes to reduce repeated computation.", benefits: "Lower cost and faster responses.", drawbacks: "Saved answers may become stale or inappropriate for a new context.", alternatives: "Real-time processing or deterministic rules." },
  { term: "Vector Database", simple: "A smart filing cabinet that finds information with similar meaning.", details: "It stores numeric representations called embeddings and searches for semantic similarity.", benefits: "Powers semantic search, recommendations, and RAG.", drawbacks: "Adds infrastructure and requires good retrieval design.", alternatives: "Keyword search or a traditional database with filters." },
  { term: "RAG", simple: "Giving AI an open-book test using trusted information before it answers.", details: "Retrieval-Augmented Generation finds relevant source material and passes it to a model as context.", benefits: "More current, grounded answers without retraining a model.", drawbacks: "Bad source material or retrieval produces bad answers.", alternatives: "Fine-tuning, long-context prompts, or curated workflows." },
  { term: "Hallucination", simple: "When AI confidently says something that is not true.", details: "The model generates information unsupported by its input or reliable evidence.", benefits: "None; measuring it helps teams track reliability.", drawbacks: "It can mislead users and damage trust.", alternatives: "RAG, citations, constrained answers, and human review." },
  { term: "Tokens", simple: "Small pieces of text that an AI reads and writes.", details: "Models split text into tokens, which providers also use for limits and pricing.", benefits: "Makes usage measurable.", drawbacks: "Counts are unintuitive and differ by model and language.", alternatives: "Word, character, or request-based limits." },
  { term: "Fine-tuning", simple: "Extra training that makes an existing AI better at one specific job.", details: "A model is updated using curated examples for a narrower task or behavior.", benefits: "More consistent specialized outputs and shorter prompts.", drawbacks: "Needs quality data, evaluation, and ongoing maintenance.", alternatives: "Prompt engineering, RAG, or few-shot examples." },
  { term: "Embeddings", simple: "Turning meaning into numbers so AI can compare information.", details: "Embeddings are numeric vectors used to find related content.", benefits: "Useful for search, clustering, recommendations, and RAG.", drawbacks: "They require storage and do not explain similarity decisions.", alternatives: "Keyword search, metadata filters, or rules." },
  { term: "Context Window", simple: "How much information an AI can keep in mind at once.", details: "It is the maximum number of tokens a model can process in one request.", benefits: "Larger windows can handle longer documents and conversations.", drawbacks: "More context costs more and does not guarantee better attention.", alternatives: "Summarization, RAG, or conversation memory." },
  { term: "AI Agent", simple: "AI that can choose steps and use tools to reach a goal.", details: "An agent combines a model with instructions and tools for multi-step tasks.", benefits: "Can automate workflows involving several decisions.", drawbacks: "Harder to predict, test, and control than a simple chatbot.", alternatives: "Fixed workflows, rule engines, or standard chatbots." },
  { term: "Guardrails", simple: "Rules and checks that keep AI answers safe and useful.", details: "They validate inputs and outputs against safety, policy, quality, and business requirements.", benefits: "Improves safety, consistency, and compliance.", drawbacks: "Can block useful responses and needs continual tuning.", alternatives: "Human moderation, strict prompts, or limited access." }
];
var models = [
  { name: "GPT-4", provider: "OpenAI", type: "text", pricing: "paid", priceDetails: "$0.03 per 1K input tokens and $0.06 per 1K output tokens", useCases: "customer support, content generation, coding, analysis", strengths: "Strong reasoning and instruction following", limitations: "Can be expensive at high volume and sometimes verbose" },
  { name: "Claude 3.5 Sonnet", provider: "Anthropic", type: "text", pricing: "paid", priceDetails: "$3 per million input tokens and $15 per million output tokens", useCases: "complex reasoning, analysis, writing, coding", strengths: "Strong analysis, safety, and clear writing", limitations: "Availability varies and its ecosystem is smaller" },
  { name: "Gemini Pro", provider: "Google", type: "multimodal", pricing: "freemium", priceDetails: "A limited free tier with paid higher usage", useCases: "text generation, image analysis, multimodal tasks", strengths: "Handles images and text and integrates with Google services", limitations: "Free usage is limited and output quality can vary" },
  { name: "Whisper", provider: "OpenAI", type: "voice", pricing: "free", priceDetails: "Open source and free to self-host", useCases: "speech-to-text, transcription, voice interfaces", strengths: "Accurate, multilingual transcription", limitations: "Requires technical setup and basic versions lack real-time streaming" }
];

// src/lib/mcp/tools/explain-jargon.ts
var explain_jargon_default = defineTool({
  name: "explain_ai_jargon",
  title: "Explain AI jargon",
  description: "Explain an AI term simply, including benefits, drawbacks, and alternatives.",
  inputSchema: { query: z.string().trim().min(1).max(100).describe("The AI term or phrase to explain.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const needle = query.toLowerCase();
    const matches = glossary.filter((entry) => entry.term.toLowerCase().includes(needle) || needle.includes(entry.term.toLowerCase())).slice(0, 5);
    if (matches.length === 0) return { content: [{ type: "text", text: `Promptly does not have an explanation for \u201C${query}\u201D yet.` }], structuredContent: { matches: [] } };
    return { content: [{ type: "text", text: JSON.stringify(matches, null, 2) }], structuredContent: { matches } };
  }
});

// src/lib/mcp/tools/find-models.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z2 } from "npm:zod@^4.6.2";
var find_models_default = defineTool2({
  name: "find_ai_models",
  title: "Find AI models",
  description: "Recommend AI models for a product use case with pricing, strengths, and limitations.",
  inputSchema: { useCase: z2.string().trim().min(3).max(1e3).describe("What the product manager wants AI to do.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ useCase }) => {
    const query = useCase.toLowerCase();
    let matches = models.filter((model) => `${model.type} ${model.useCases}`.toLowerCase().split(/[ ,]+/).some((word) => word.length > 3 && query.includes(word)));
    if (query.includes("voice") || query.includes("speech") || query.includes("transcri")) matches = models.filter((model) => model.type === "voice");
    else if (query.includes("image") || query.includes("visual")) matches = models.filter((model) => model.type === "multimodal");
    else if (query.includes("support") || query.includes("chat") || query.includes("text")) matches = models.filter((model) => model.type === "text" || model.type === "multimodal");
    if (matches.length === 0) matches = models.filter((model) => model.type === "text" || model.type === "multimodal");
    const recommendations = matches.slice(0, 3);
    return { content: [{ type: "text", text: JSON.stringify(recommendations, null, 2) }], structuredContent: { recommendations } };
  }
});

// src/lib/mcp/tools/latest-nuggets.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z3 } from "npm:zod@^4.6.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.116.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function projectUrl() {
  const value = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!value) throw new Error("Promptly's news service is not configured.");
  return value;
}
function publishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (value) => typeof value === "string" && value.startsWith("sb_publishable_")
        );
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (!legacy) throw new Error("Promptly's public news access is not configured.");
  return legacy;
}
function supabaseAnon() {
  return createClient(projectUrl(), publishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/latest-nuggets.ts
var latest_nuggets_default = defineTool3({
  name: "latest_ai_nuggets",
  title: "Latest AI nuggets",
  description: "Get Promptly's latest public AI news, simplified for product managers.",
  inputSchema: { limit: z3.number().int().min(1).max(10).default(5).describe("Number of stories to return.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ limit }) => {
    const { data, error } = await supabaseAnon().from("news_items").select("title,summary,simple_explanation,relevance_to_pm,pm_use_cases,pricing_comparison,published_date,source_name,source_url").order("published_date", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: `Could not load nuggets: ${error.message}` }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: { nuggets: data ?? [] } };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "promptly-ai-for-pms",
  title: "promptly-ai-for-pms",
  version: "0.1.0",
  instructions: "Promptly helps product managers understand current AI news, jargon, and model choices. Use these read-only tools for simple, practical answers. Never imply access to private feedback or user data.",
  tools: [latest_nuggets_default, explain_jargon_default, find_models_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
